import { createHash } from "node:crypto";
import { cp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const project = resolve(here, "../../..");
const packageRoot = resolve(here, "..");
const source = join(packageRoot, "src");
const distribution = join(packageRoot, "node_modules", "pdfjs-dist");
const output = join(project, "assets", "pdfjs");
const expectedVersion = "5.7.284";

function assertInside(parent, child) {
  const path = relative(parent, child);
  if (path === "" || path.startsWith(`..${sep}`) || path === "..") {
    throw new Error(`unsafe generated path: ${child}`);
  }
}

async function filesUnder(directory, prefix = "") {
  const result = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) result.push(...await filesUnder(join(directory, entry.name), relativePath));
    else result.push(relativePath);
  }
  return result.sort();
}

function mime(path) {
  if (path.endsWith(".html")) return "text/html; charset=utf-8";
  if (path.endsWith(".mjs") || path.endsWith(".js")) return "text/javascript; charset=utf-8";
  if (path.endsWith(".json")) return "application/json";
  if (path.endsWith(".bcmap")) return "application/octet-stream";
  if (path.endsWith(".pfb")) return "application/octet-stream";
  if (path.endsWith(".ttf")) return "font/ttf";
  if (path.endsWith(".wasm")) return "application/wasm";
  return "application/octet-stream";
}

const metadata = JSON.parse(await readFile(join(distribution, "package.json"), "utf8"));
if (metadata.version !== expectedVersion) throw new Error(`expected PDF.js ${expectedVersion}, got ${metadata.version}`);
assertInside(project, output);
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
for (const [from, to] of [
  [join(distribution, "legacy", "build", "pdf.mjs"), join(output, "pdf.mjs")],
  [join(distribution, "legacy", "build", "pdf.worker.mjs"), join(output, "pdf.worker.mjs")],
  [join(distribution, "cmaps"), join(output, "cmaps")],
  [join(distribution, "standard_fonts"), join(output, "standard_fonts")],
  [join(distribution, "wasm"), join(output, "wasm")],
  [join(distribution, "LICENSE"), join(output, "LICENSE.pdfjs")],
  [join(source, "viewer.html"), join(output, "viewer.html")],
  [join(source, "viewer.mjs"), join(output, "viewer.mjs")],
]) {
  await cp(from, to, { recursive: true });
}

const files = (await filesUnder(output)).filter((path) => !["manifest.json", "routes.rs"].includes(path));
const manifest = { pdfjsVersion: expectedVersion, files: [] };
const routes = [
  "// @generated by web/pdf/scripts/build.mjs; do not edit by hand.",
  "pub(super) fn get(path: &str) -> Option<(&'static str, &'static [u8])> {",
  "    match path {",
];
for (const path of files) {
  const bytes = await readFile(join(output, ...path.split("/")));
  const mediaType = mime(path);
  manifest.files.push({ path, mediaType, bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") });
  routes.push(`        ${JSON.stringify(path)} => Some((${JSON.stringify(mediaType)}, include_bytes!(${JSON.stringify(`./${path}`)}))),`);
}
routes.push("        _ => None,", "    }", "}", "");
await writeFile(join(output, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
await writeFile(join(output, "routes.rs"), `${routes.join("\n")}\n`);
